---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: 'Nach der Installation Ihrer AFX-Hardware können Sie die ONTAP-Cluster-Einrichtung abschließen. Dieser Prozess umfasst verwandte Konfigurationsphasen, die Sie nacheinander durchführen sollten. Im Rahmen dessen können Sie optional die Datenrechenknoten (DCNs) hinzufügen, die die AI Data Engine (AIDE) ausführen, sodass der AFX-Speichercluster und der DCN-Cluster als ein einziges System betrieben werden, das über dieselbe ONTAP-Steuerungsebene verwaltet wird.' 
---
= Richten Sie Ihren AFX-Speichersystem- ONTAP Cluster ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Installation Ihrer AFX-Hardware können Sie die ONTAP-Cluster-Einrichtung abschließen. Dieser Prozess umfasst verwandte Konfigurationsphasen, die Sie nacheinander durchführen sollten. Im Rahmen dessen können Sie optional die Datenrechenknoten (DCNs) hinzufügen, die die AI Data Engine (AIDE) ausführen, sodass der AFX-Speichercluster und der DCN-Cluster als ein einziges System betrieben werden, das über dieselbe ONTAP-Steuerungsebene verwaltet wird.



== Bereiten Sie die Einrichtung eines AFX-Speichersystems vor

Bevor Sie Ihren ONTAP Cluster einrichten, sollten Sie die grundlegenden AFX-Anforderungen und zusätzliche AIDE-Überlegungen überprüfen, um sicherzustellen, dass Sie über alle notwendigen Informationen und Ressourcen verfügen, um den Einrichtungsprozess erfolgreich abzuschließen.



=== Kernanforderungen von AFX

Bei der Einrichtung Ihres AFX-Clusters sind mehrere grundlegende Anforderungen zu beachten.

.Hardwareinstallation
Stellen Sie sicher, dass Sie die Hardwareinstallation Ihres AFX-Systems abgeschlossen haben. Weitere Informationen finden Sie unter link:../install-setup/install-setup-workflow.html["Installieren Sie Ihr AFX-System"].

.Grundlegende IP-Adressierung
Sie benötigen die folgende IP-Adressierungskonfiguration:

* IP-Adresse für die Clusterverwaltung
+
Die Clusterverwaltungs-IP-Adresse ist eine eindeutige IPv4-Adresse für die Clusterverwaltungsschnittstelle, die vom Clusteradministrator verwendet wird, um auf die Admin-SVM zuzugreifen und den Cluster zu verwalten.  Diese IP-Adresse erhalten Sie von dem Administrator, der in Ihrer Organisation für die Vergabe von IP-Adressen zuständig ist.

* Netzwerk-Subnetzmaske
+
Während der Clustereinrichtung benötigt ONTAP eine Reihe von Netzwerkschnittstellen, die für Ihre Konfiguration geeignet sind.  Sie können die Empfehlung bei Bedarf anpassen.



.Zusätzliche Netzwerkkonfiguration
Sie benötigen außerdem die folgenden zugehörigen Netzwerkinformationen:

* IP-Adresse des Netzwerk-Gateways
* DNS-Domänennamen
* IP-Adressen des DNS-Nameservers
* NTP-Server-IP-Adressen
* Subnetzmaske




=== Weitere AIDE-Überlegungen

Bei der erstmaligen Installation und Einrichtung von AFX können Sie optional die NetApp AI Data Engine (AIDE) einbinden. AIDE unterstützt zwei Bereitstellungsmodelle: AIDE Software auf Servern von Drittanbietern oder von NetApp bereitgestellte Data Compute Nodes (DCNs). Wenn Sie planen, AIDE einzurichten, erfüllen Sie zunächst die Voraussetzungen für Ihr Bereitstellungsmodell:

* Für Serverbereitstellungen von Drittanbietern führen Sie  https://docs.netapp.com/us-en/ai-data-engine/install-aide-server/aide-mde-server-hardware-requirements.html["Hardwareinstallation für AI Data Engine auf Servern von Drittanbietern"^] aus und dann  https://docs.netapp.com/us-en/ai-data-engine/install-setup/install-aide-as-software.html["AIDE-Software auf Servern von Drittanbietern installieren"^].
* Für NetApp DCN Implementierungen vollständig ausfüllen https://docs.netapp.com/us-en/ai-data-engine/install-dcn/aide-dcn-hardware-requirements.html["Hardwareinstallation für AI Data Engine auf NetApp-bereitgestellten Datenrechenknoten"^].
* Ermitteln Sie die Adressen und die zugehörige Netzwerkkonfiguration der Rechenknoten.




== Durchführen der ersten Clustereinrichtung

Sie können Ihr Laptop-Gerät mit dem AFX-Cluster verbinden und mehrere globale Konfigurationseinstellungen festlegen.

.Informationen zu diesem Vorgang
Es gibt vier Bereiche des AFX-Clusters, die zunächst konfiguriert werden müssen.  Die ersten drei sind erforderlich, während der letzte optional ist.

.Schritte
. Entdecken Sie Ihr Clusternetzwerk.
+
.. Verbinden Sie Ihren Laptop mit dem Verwaltungsswitch und greifen Sie auf die Netzwerkcomputer und -geräte zu.
.. Öffnen Sie den Datei-Explorer.
.. Wählen Sie *Netzwerk*, klicken Sie dann mit der rechten Maustaste und wählen Sie *Aktualisieren*.
.. Wählen Sie eines der ONTAP -Symbole aus und akzeptieren Sie dann alle auf Ihrem Bildschirm angezeigten Zertifikate.
+
Die Benutzeroberfläche des System Managers wird angezeigt.



. Legen Sie das Administratorkennwort fest.
+
Geben Sie das Passwort für die `admin` Konto. Wählen Sie *Weiter*.

. Konfigurieren Sie die IP-Adressen für den AFX Cluster und die Controller-Knoten.
+
Geben Sie IP-Adressen und Subnetzmasken an.

. Wenn Sie AI Data Engine mit Ihrem AFX-Speichersystem installieren, geben Sie die IP-Adressen für die drei Rechenknoten an.
. Konfigurieren Sie die Netzwerkdienste einschließlich DNS und NIS. Wählen Sie *Weiter*.
+
Definieren Sie die Details für Ihre DNS- und NTP-Server.

. Optional können Sie eine Verschlüsselung einrichten.
+
Sie können die Details für die Cluster-Verschlüsselung definieren. Wählen Sie *Weiter*.

+

NOTE: Informationen zum Erstellen eines Clusters für eine Nicht-Windows-Umgebung finden Sie unter link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html["Erstellen Sie einen ONTAP Cluster und verbinden Sie Knoten."^]Die



.Was kommt als nächstes
Sie werden zur Anmeldeseite des Systemmanagers weitergeleitet.  Führen Sie die in<<Vollständige Clustereinrichtung>> .



== Vollständige Clustereinrichtung

Nachdem die Erstkonfiguration durchgeführt wurde, können Sie die Einrichtung des ONTAP Clusters mit dem System Manager abschließen.

.Informationen zu diesem Vorgang
Während der Einrichtung werden drei Bereiche des AFX-System ONTAP Clusters konfiguriert.  Füllen Sie nach Möglichkeit alle drei aus, aber nur der erste ist erforderlich.

.Bevor Sie beginnen
Sie benötigen folgende Informationen:

* VLAN-Konfigurationsdetails.
* NAS- und/oder S3-Konfigurationsdetails.


.Schritte
. Sign in , das Sie bei der Ersteinrichtung des Clusters angegeben haben.  Beachten Sie das Popup-Fenster oben rechts mit drei Konfigurationsoptionen.
. Wählen Sie *VLAN und Tagging* und wählen Sie die für Ihre Umgebung geeigneten Netzwerkoptionen.
. Wählen Sie *Netzwerkdienste* und konfigurieren Sie die Clientzugriffsprotokolle für die Standarddaten-SVM.
. Wählen Sie *Datencontainer* und erstellen Sie ein Volume oder einen S3-Bucket.


.Was kommt als nächstes
* Wenn Sie AIDE im Rahmen der AFX-Clusterkonfiguration eingebunden haben, führen Sie die zusätzlichen AIDE-Konfigurationsschritte durch. Die Authentifizierungskonfiguration gilt für alle AIDE-Bereitstellungen. Für NetApp DCN-Bereitstellungen, die lizenzierte AIDE-Funktionen nutzen, ist eine Lizenzierung erforderlich; Serverbereitstellungen von Drittanbietern sind metadatenorientiert und benötigen keine AIDE-Lizenz. Siehe  https://docs.netapp.com/us-en/ai-data-engine/install-setup/cluster-setup-afx.html["AI Data Engine einrichten"^] für weitere Informationen.
* Du solltestlink:../get-started/prepare-cluster-admin.html["Vorbereiten der AFX-Verwaltung"] bevor Sie Ihren AFX-Cluster in einer Produktionsumgebung verwenden.




== Ähnliche Informationen

* link:../get-started/learn-about-aide.html["Erfahren Sie mehr über die NetApp AI Data Engine"]
* link:../administer/configure-svm.html["Konfigurieren einer AFX SVM"]
* link:../get-started/prepare-cluster-admin.html["Vorbereiten der AFX-Verwaltung"]

