---
sidebar: sidebar 
permalink: faq-ontap-afx.html 
keywords: afx, afx system, faq, frequently asked questions 
summary: Diese FAQ-Liste bietet Antworten auf Fragen, die Kunden typischerweise zu ihrem AFX-Speichersystem haben.  Es enthält Konzepte und Terminologie, die hilfreich sein können, wenn Sie AFX genauer erkunden oder erweiterte Verwaltungsaufgaben ausführen. 
---
= FAQ zu AFX-Speichersystemen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Diese FAQ-Liste bietet Antworten auf Fragen, die Sie möglicherweise zu Ihrem AFX-Speichersystem haben.  Es enthält Konzepte und Terminologie, die hilfreich sein können, wenn Sie AFX genauer erkunden oder erweiterte Verwaltungsaufgaben ausführen.



== Allgemein

.Was ist eine ONTAP Persönlichkeit?
ONTAP ist eine robuste und vielseitige Speicherplattform, die für ihren umfassenden Funktionsumfang und ihre Anpassungsfähigkeit an eine Vielzahl von Speicheranforderungen bekannt ist.  Diese Flexibilität macht es zu einer ausgezeichneten Wahl für Unternehmen mit unterschiedlichen Arbeitslasten, manche Kunden können jedoch von einer maßgeschneiderten Speicherlösung profitieren, die für die Anforderungen ihrer spezifischen Umgebung optimiert ist.

Um diesen speziellen Anforderungen gerecht zu werden, bieten einige NetApp Speichersysteme unterschiedliche ONTAP Persönlichkeiten, von denen jede einen Funktionsumfang umfasst, der auf die Unterstützung der individuellen Kundenanforderungen ausgelegt ist.  Eine ONTAP Persönlichkeit ist typischerweise eine Kombination aus Hardware- und Softwarefunktionen und wurde speziell entwickelt, um ein optimiertes Erlebnis für gezielte Anwendungsfälle zu bieten.  NetApp bietet drei ONTAP -Persönlichkeiten:

* *Unified ONTAP* – Die Unified ONTAP Persönlichkeit bietet eine breite Palette an Datenverwaltungsfunktionen und unterstützt NAS-, SAN- und S3-Protokolle für maximale Flexibilität. Dies ist das Flaggschiff-Angebot von NetApp , verfügbar auf AFF und FAS -Systemen sowie virtualisierten Bereitstellungen wie ONTAP Select und Cloud Volumes ONTAP.
* *AFX* – Die AFX ONTAP Persönlichkeit bietet eine disaggregierte Lösung, die entwickelt wurde, um die strengen Anforderungen von Hochleistungs-NAS- und S3-Workloads, einschließlich KI/ML-Anwendungen, zu erfüllen. AFX-Systeme bieten spezielle Funktionen für Kunden, die skalierbaren Datei- und Objektspeicher mit hohem Durchsatz benötigen.
* * ASA r2* – Die ASA r2 ONTAP Persönlichkeit bietet eine disaggregierte Lösung, die speziell für reine SAN-Umgebungen entwickelt wurde. https://docs.netapp.com/us-en/asa-r2/["ASA r2-Systeme"^]  Optimieren Sie die Speichererfahrung für Block-Workloads und bieten Sie vereinfachte Verwaltung und optimierte Leistung für SAN-Kunden.


Durch das Angebot dieser unterschiedlichen ONTAP -Persönlichkeiten ermöglicht NetApp Unternehmen die Auswahl einer Speicherlösung, die auf ihre Betriebsanforderungen und Anwendungs-Workloads abgestimmt ist.

.Kann ich die ONTAP Persönlichkeit meines NetApp Speichersystems ändern?
Nein. Die Persönlichkeit Ihres ONTAP Speichersystems ist unveränderlich und kann nicht geändert werden.  Beispielsweise können Sie ein FAS oder AFF -Speichersystem (auf dem die Unified ONTAP Persönlichkeit ausgeführt wird) nicht in ein AFX-Speichersystem konvertieren oder aktualisieren.

.Die System Manager-Schnittstellen für die verschiedenen ONTAP -Persönlichkeiten sehen alle sehr ähnlich aus.  Wie kann ich die Persönlichkeit eines bestimmten Systems bestimmen?
Wählen Sie im System Manager im linken Navigationsbereich *Cluster* und dann *Übersicht* aus.  Sie sehen die auf der Seite angezeigte Persönlichkeit.  Alternativ können Sie den Befehl „system node show“ an der CLI ausgeben.  Sie können die Persönlichkeit eines ONTAP Clusters auch mithilfe der REST-API bestimmen; siehelink:./rest/first-call.html["Ihr erster REST-API-Aufruf des AFX-Systems"] für Details.

.Seit wann sind die AFX-Speichersysteme verfügbar? Welche ist die früheste ONTAP Version, die mit AFX unterstützt wird?
Das AFX-Speichersystem wurde auf der NetApp Insight -Konferenz im Oktober 2025 angekündigt. AFX unterstützt ONTAP 9.17.1 und spätere Versionen. Weitere Informationen erhalten Sie von Ihrem NetApp Vertriebsmitarbeiter.

.Was bedeutet „disaggregiert“ im Kontext von AFX-Speichersystemen?
Der Begriff „disaggregiert“ kann bei AFX je nach Kontext zwei unterschiedliche, aber verwandte Bedeutungen haben.

Ein wichtiges Konzept ist zunächst die Entkopplung der Rechenleistung in den Controllerknoten von den Speicherregalen.  Mit AFX sind die Rechen- und Speicherkomponenten des Clusters nicht mehr so ​​eng miteinander verbunden wie bei FAS und AFF -Systemen, auf denen die Unified ONTAP -Persönlichkeit ausgeführt wird.  Stattdessen sind sie über Cluster-Switches verbunden.  Jeder AFX-Knotencontroller verfügt über eine vollständige Ansicht des gesamten Cluster-Speicherpools.

Das zweite verwandte Konzept mit disaggregiertem Speicher besteht darin, dass die Aggregate und die RAID-Verwaltung als verwaltbare Einheiten entfernt werden.  Eine Speicherabstraktionsschicht innerhalb von AFX konfiguriert und verwaltet automatisch die Low-Level-Aspekte des Speichers, einschließlich der physischen Festplatten und RAID-Gruppen.  Dadurch kann sich der AFX-Administrator auf die übergeordnete Speicherkonfiguration basierend auf Volumes und Buckets konzentrieren.



== Interoperabilität

.Kann ich AFX-Systemknoten mit AFF, ASA oder FAS Systemknoten im selben ONTAP Cluster mischen?
Nein. Sie können keine Systemknoten mit unterschiedlichen ONTAP Persönlichkeiten im selben Cluster mischen. Beispielsweise können Sie AFX-Knoten (auf denen die AFX ONTAP Persönlichkeit ausgeführt wird) nicht mit AFF oder FAS -Knoten (auf denen die Unified ONTAP Persönlichkeit ausgeführt wird) im selben Cluster mischen.

.Kann ich FlexCache mit einem AFX-Systemcluster verwenden?
Ja. AFX-Speichersysteme unterstützen FlexCache sowohl zu als auch von einem AFF oder FAS System, auf dem die Unified ONTAP Persönlichkeit ausgeführt wird. Die einzige Einschränkung besteht darin, dass FlexCache mit Write-Back-Modus mit AFX nicht unterstützt wird.

.Wenn ich ein AFF oder FAS -System (auf dem die Unified ONTAP Persönlichkeit ausgeführt wird) mit einem AFX-System für SnapMirror oder FlexCache verwenden möchte, welche ONTAP Version benötige ich?
Die SnapMirror -Versionsregeln für AFX sind identisch mit Unified ONTAP.  Dies bedeutet, dass das Quellsystem zum Replizieren von Unified ONTAP innerhalb des unterstützten Versionsbereichs liegen muss.  Für die Replikation von AFX muss das Unified ONTAP -System ONTAP 9.16.1 oder höher aufweisen (die früheste Version, die die Funktion „Advanced Capacity Balancing“ unterstützt).  Für FlexCache gelten für Quell- und Zielsysteme die gleichen Regeln wie in https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743"^] .

Es gibt einige Unterschiede bei der Unterstützung von FlexGroup -Volumes.  Ein FlexGroup -Volume auf AFX kann kein Ursprungsvolume für ein FlexCache -Volume sein, das den Writeback-Modus verwendet.

.Kann ich ONTAPI (ZAPI)-API-Aufrufe an einen AFX-Cluster senden?
Nein. Mit AFX wird nur die ONTAP REST API unterstützt.  Jeder Automatisierungscode, der ZAPI verwendet, muss zur Verwendung mit AFX in die REST-API konvertiert werden.



== Erweiterte Konzepte

.Welche Datenprotokolle werden von einem AFX-Speichersystem unterstützt?
Zu den von AFX unterstützten Datenprotokollen gehören die folgenden:

* NFSv3, NFSv4.0, NFSv4.1, NFSv4.2
* SMB2.x, SMB3.x
* S3
* NDMP


.Funktionieren die Datenprotokolle in AFX anders?
Nein. Die Datenprotokolle in AFX funktionieren auf die gleiche Weise wie bei AFF und FAS Systemen.

.Wird Advanced Disk Partitioning (ADP) in AFX verwendet?
Nein. ADP wird nicht mit AFX verwendet.  Da es bei AFX keine Root-Aggregate gibt, ist die ADP-Funktion zur Maximierung der Speicherplatzeffizienz nicht erforderlich.

.Kann ich für mein AFX-Speichersystem im Backend-Clusternetzwerk beliebige Switchtypen verwenden?
Nein. Für das Clusternetzwerk werden nur Switches unterstützt, die speziell für die AFX-Speicherplattform zugelassen und mit dieser bereitgestellt sind. Außerdem sind diese Backend-Switches für AFX-Clustervorgänge vorgesehen. Die Clientzugriffsvorgänge (mit NFS, SMB und S3) sollten nur über das Frontend-Clientdatennetzwerk ausgeführt werden.

.Wie sind die Cluster-Switches konfiguriert?
Die Cluster-Netzwerk-Switches werden mithilfe einer von NetApp bereitgestellten Konfigurationsdatei konfiguriert. Änderungen an der Konfigurationsdatei werden nicht unterstützt.

.Wie ist der Speicher in einem AFX-Cluster organisiert?
Alle an einen AFX-Cluster angeschlossenen Festplatten und Speicherregale sind Teil einer Storage Availability Zone (SAZ).  Jeder AFX-Cluster unterstützt nur eine SAZ, die nicht über mehrere AFX-Cluster hinweg gemeinsam genutzt werden kann (mit Ausnahme von SnapMirror Replikation und FlexCache -Vorgängen).

Jeder Knoten hat Einblick in den gesamten Speicher in der SAZ.  Wenn einem Cluster Speicherregale hinzugefügt werden, fügt ONTAP die Festplatten automatisch hinzu.

.Wie werden Daten in einem AFX-Cluster verteilt?
Sobald Daten zugeordnet sind, können sie auf einer beliebigen Festplatte in der SAZ abgelegt werden.  Sobald die Daten platziert sind, müssen sie nicht mehr verschoben werden.  Auf Basis der zugrunde liegenden Daten wird ein Volume erstellt und einem bestimmten Knoten zugewiesen.  Die Volumina können von AFX verschoben werden, typischerweise im Rahmen eines Ausgleichsprozesses.  Dies beeinflusst, welcher NVRAM des Knotens die Schreibvorgänge auf die Festplatte ausführt.  Durch eine Volume-Verschiebung ändert sich, welcher Knoten das Volume besitzt, die Daten selbst können aber an ihrem ursprünglichen Platz bleiben.

.Wie verwaltet AFX die Volumen innerhalb der SAZ?
AFX enthält eine Funktion namens Automated Topology Management (ATM), die auf Ungleichgewichte zwischen System- und Benutzerobjekten reagiert.  Das Hauptziel von ATM besteht darin, die Volumina im gesamten AFX-Cluster auszugleichen.  Wenn ein Ungleichgewicht erkannt wird, wird ein interner Job ausgelöst, um die Daten gleichmäßig auf die aktiven Knoten zu verteilen.  Die Daten werden mithilfe von ZCVM neu zugewiesen, wobei nur die Objektmetadaten kopiert und aktualisiert werden müssen.

.Wie werden Volumes auf den Knoten in einem AFX-Cluster platziert?
NetApp AFX gleicht die Platzierung von Volumes automatisch auf alle Knoten in einem Cluster aus.  Ab ONTAP 9.18.1 wurde der Platzierungsalgorithmus so verbessert, dass er die Leistung der Knoten beim Platzieren oder Verschieben von Volumen berücksichtigt.  Dies führt zu einer verbesserten Leistungsverteilung über die Knoten im AFX-Cluster und verringert die Wahrscheinlichkeit einer Überlastung einzelner Knoten erheblich.  Bei früheren AFX-Versionen basierte die Platzierung auf der Gesamtzahl der Volumes im Cluster.  Jedem Knoten wird unabhängig von der Aktivität die gleiche Anzahl an Datenträgern zugewiesen.

.Wie funktionieren Volume-Verschiebungsvorgänge mit AFX anders als mit AFF oder FAS Systemen?
Mit AFF und FAS -Systemen, auf denen die Unified ONTAP Persönlichkeit ausgeführt wird, ist es möglich, ein Volume unterbrechungsfrei von einem Knoten oder Aggregat zu einem anderen im Cluster zu verschieben. Dies wird mithilfe eines Hintergrundkopiervorgangs mit SnapMirror -Technologie durchgeführt.  Am Zielort wird ein neues Zielvolume erstellt.  Je nach Größe des Datenträgers und Auslastung der Clusterressourcen kann die Dauer eines Datenträgerverschiebungsvorgangs variieren.

Bei AFX gibt es keine Aggregate. Der gesamte Speicher befindet sich in einer einzigen Storage Availability Zone (SAZ), die von jedem Knoten im Cluster aus zugänglich ist. Daher müssen die Daten bei Volume-Verschiebungen nie wirklich kopiert werden.  Stattdessen werden alle Volumenverschiebungen durch Zeigeraktualisierungen zwischen den Knoten durchgeführt. Dies wird als Zero Copy Volume Move (ZCVM) bezeichnet und geschieht sofort, da keine Daten tatsächlich kopiert oder verschoben werden. Dies ist im Wesentlichen derselbe Volume-Verschiebungsvorgang, der mit Unified ONTAP ohne die SnapMirror Kopie verwendet wird.

In der ersten AFX-Version 9.17.1 werden Volumes nur in Szenarien der Speicherausfallwiederherstellung und beim Hinzufügen oder Entfernen von Knoten aus dem Cluster verschoben. Diese Bewegungen werden nur über ONTAP gesteuert.
