---
sidebar: sidebar 
permalink: protect-data/create-peer-relationship.html 
keywords: afx, afx system, peering, peer relationship 
summary: 'Eine Peer-Beziehung definiert Netzwerkverbindungen, die Clustern und virtuellen Speichermaschinen (VMs) den sicheren Datenaustausch ermöglichen. Sie können eine Peer-Beziehung zwischen Speicher-VMs auf verschiedenen Clustern erstellen, um Datenschutz und Notfallwiederherstellung mit SnapMirror zu ermöglichen.' 
---
= Erstellen einer Intercluster-SVM-Peer-Beziehung auf einem AFX-Speichersystem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Peer-Beziehung definiert Netzwerkverbindungen, die Clustern und virtuellen Speichermaschinen (VMs) den sicheren Datenaustausch ermöglichen. Sie können eine Peer-Beziehung zwischen Speicher-VMs auf verschiedenen Clustern erstellen, um Datenschutz und Notfallwiederherstellung mit SnapMirror zu ermöglichen.

.Bevor Sie beginnen
Sie müssen eine Cluster-Peer-Beziehung zwischen dem lokalen und dem Remote-Cluster hergestellt haben, bevor Sie eine Speicher-VM-Peer-Beziehung erstellen können. link:snapshot-replication.html#step-1-create-a-cluster-peer-relationship["Erstellen einer Cluster-Peer-Beziehung"] falls Sie dies nicht bereits getan haben.

.Schritte
. Wählen Sie im System Manager *Schutz > Übersicht*.
. Wählen Sie unter *Storage-VM-Peers* die Option *Einen Storage-VM-Peer hinzufügen* aus.
. Wählen Sie die Speicher-VM auf dem lokalen Cluster und dann die Speicher-VM auf dem Remote-Cluster aus.
. Wählen Sie *Einen Speicher-VM-Peer hinzufügen*.


.Ähnliche Informationen
* https://docs.netapp.com/us-en/ontap/peering/peering-basics-concept.html["Erfahren Sie mehr über Peer-Beziehungen"^] .

