---
sidebar: sidebar 
permalink: get-started/compare-unified-ontap.html 
keywords: afx, afx system, compare afx, compare unified ontap 
summary: 'NetApp AFX-Systeme führen eine angepasste ONTAP -Persönlichkeit aus, die sich von der ONTAP Persönlichkeit (als Unified ONTAP bezeichnet) unterscheidet, die auf AFF und FAS -Speicher ausgeführt wird.  Sie sollten sich darüber im Klaren sein, dass AFX-Systeme FAS und AFF Systemen ähneln und sich von ihnen unterscheiden.  Dies bietet eine wertvolle Perspektive und kann bei der Bereitstellung von AFX in Ihrer Umgebung hilfreich sein.' 
---
= Vergleichen Sie das AFX-Speichersystem mit AFF und FAS -Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX-Systeme führen eine angepasste ONTAP -Persönlichkeit aus, die sich von der ONTAP Persönlichkeit (als Unified ONTAP bezeichnet) unterscheidet, die auf AFF und FAS -Speicher ausgeführt wird.  Sie sollten sich darüber im Klaren sein, dass AFX-Systeme FAS und AFF Systemen ähneln und sich von ihnen unterscheiden.  Dies bietet eine wertvolle Perspektive und kann bei der Bereitstellung von AFX in Ihrer Umgebung hilfreich sein.


TIP: Die AFX-Dokumentation enthält Links zu verschiedenen Themen auf der Unified ONTAP Dokumentationssite mit Details zu Funktionen, die sich unabhängig von der ONTAP Persönlichkeit gleich verhalten.  Die zusätzlichen Inhalte bieten mehr Tiefe, die bei der Verwaltung Ihres AFX-Speichersystems hilfreich sein kann.



== Konfigurationsunterschiede

Es gibt einige Bereiche, in denen sich die AFX-Konfiguration von AFF und FAS Systemen unterscheidet.

Erweiterter Kapazitätsausgleich:: Die erweiterte Kapazitätsausgleichsfunktion, gesteuert über `-gdd` CLI-Parameter, ist standardmäßig für alle FlexGroup -Volumes aktiviert.




== Nicht unterstützte oder eingeschränkte Unified ONTAP Funktionen

NetApp AFX ist für leistungsstarke NAS- und Objekt-Workloads optimiert.  Aus diesem Grund gibt es Unterschiede zu AFF und FAS sowie zu den anderen Unified ONTAP Speichersystemen.  Die folgenden Funktionen sind mit dem NetApp AFX nicht verfügbar; die Liste ist nach Hauptfunktionen oder Funktionsbereich geordnet.  Sie sollten auch die Aktualisierungen und Änderungen für AFX überprüfen.link:../release-notes/whats-new-9171.html["Was ist neu"] basierend auf Ihrer Freigabe.



=== Block und SAN

* SAN-Administration und Client-Zugriff
* LUNs und NVMe-Namensräume
* Dicke Bereitstellung von Volumen




=== Zuschlagstoffe und physische Lagerung

* MetroCluster
* Physische, knoteneigene Aggregate
* RAID-Verwaltung
* NetApp Aggregate Encryption (NAE)
* Deduplizierung auf Aggregatebene
* SyncMirror (Aggregatspiegelung)
* FabricPool -Stufen




=== Datenreplikation (SnapMirror)


NOTE: Die Datenreplikation zwischen Unified ONTAP und AFX wird in beide Richtungen unterstützt, wobei die gleichen Versionsbeschränkungen gelten, die in [Referenz einfügen] beschrieben sind. https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["Kompatible ONTAP Versionen für SnapMirror -Beziehungen"^] (mit wenigen kleineren Ausnahmen).

* Keine Replikation eines Volumes von einem AFF oder FAS System, das einen LUN- oder NVMe-Namespace enthält
* FlexGroup Volumes können nur von AFX auf Unified ONTAP Version 9.16.1 oder höher repliziert werden (aufgrund der Notwendigkeit von Advanced Capacity Balancing).




=== Verwaltbarkeit

* ONTAPI-API (ZAPI)
* REST-APIs für nicht unterstützte Funktionen (wie z. B. MetroCluster)
* Einige anfängliche Einschränkungen von REST-APIs für Leistungsstatistiken
* AIQ Unified Manager-Unterstützung
* Grafana Harvest Version 25.08.1 und höher
* NetApp Trident Version 25.10 und höher




== Änderungen an der Kommandozeilenschnittstelle

Die mit AFX verfügbare ONTAP CLI spiegelt im Allgemeinen die mit AFF und FAS Systemen verfügbare CLI wider.  Es gibt jedoch mehrere Unterschiede, darunter:

* Neue AFX-Befehle im Zusammenhang mit:
+
** Anzeigen der Kapazität der Speicherverfügbarkeitszone
** Boot-Medien


* Keine SAN-bezogenen Befehle
* Aggregate-Management-Befehle sind nicht mehr erforderlich
* Die aggregierte Ansicht zeigt nun die gesamte Speicherverfügbarkeitszone (SAZ) an.




== Ähnliche Informationen

* link:../get-started/system-design.html["AFX-Systemeigenschaften"]
* link:../get-started/software-architecture.html["Details der AFX-Architektur"]
* link:../faq-ontap-afx.html["FAQ zu AFX-Speichersystemen"]
* link:../administer/additional-ontap-cluster.html["Zusätzliche AFX-Clusterverwaltung"]
* link:../administer/additional-ontap-svm.html["Zusätzliche AFX SVM-Verwaltung"]

