---
sidebar: sidebar 
permalink: get-started/system-design.html 
keywords: afx, afx system, characteristics, design 
summary: Das NetApp AFX-Speichersystem verfügt über mehrere Eigenschaften, die es ermöglichen, als leistungsstarke NAS-Plattform zu fungieren. 
---
= Eigenschaften des AFX-Speichersystems
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das NetApp AFX-Speichersystem verfügt über mehrere Eigenschaften, die es ermöglichen, als leistungsstarke NAS-Plattform zu fungieren.

Entkoppeln Sie Speicher- und Rechenkapazitäten:: Im Gegensatz zu AFF und FAS Speichersystemen sind die AFX-Speicher- und Rechenelemente des Clusters entkoppelt.  AFX-Controller sind nicht auf den Zugriff auf eine begrenzte Anzahl lokaler Festplatten beschränkt.
Entfernung der Aggregat- und RAID-Verwaltung:: Der Speicheradministrator muss die Aggregate und RAID-Gruppen nicht mehr verwalten.  AFX übernimmt diese Aufgaben, was die Verwaltung vereinfacht und Nichtspezialisten die Möglichkeit bietet, ihre Daten zu verwalten.
Einzelner Speicherpool für den Cluster:: Durch die Entkopplung von AFX-Rechenleistung und -Speicher sowie eine vereinfachte Speicherverwaltung entsteht ein einziger Speicherpool.  Diese Storage Availability Zone (SAZ) steht allen Controller-Knoten in einem AFX-Cluster zur Verfügung. Sehenlink:../faq-ontap-afx.html["FAQ zu AFX-Speichersystemen"] für weitere Details.
Hohe Leistung:: AFX ist auf die hohe Leistung ausgelegt, die spezialisierte KI/ML-Anwendungen benötigen.  Es kann moderne Hardware effizienter nutzen, um eine hohe und anhaltende Bandbreite mit extrem niedriger Latenz bereitzustellen.
Einfache Bedienung:: Der einzelne Speicherpool bietet zusammen mit anderen Funktionen, einschließlich der automatischen Speicherverwaltung, ein viel einfacheres Verwaltungs- und Betriebsmodell.
Skalierbarkeit:: Die Menge der Controllerknoten und Speicherregale in einem Cluster kann je nach Anwendungsanforderungen unabhängig erweitert werden.  Beim Hinzufügen von Controllern oder Regalen gibt es nur begrenzte Verwaltungsanforderungen und Unterbrechungen.
Verbesserte Datenmobilität:: Volumes können unterbrechungsfrei zwischen den Cluster-Controller-Knoten verschoben werden, ohne dass tatsächlich Daten kopiert werden müssen.  Stattdessen werden das Metadatenverzeichnis und die Indexzeiger aktualisiert.  Dadurch wird die Leistung bei typischen Verwaltungsvorgängen sowie die Wiederherstellung in Fehlerszenarien erheblich verbessert.

