---
sidebar: sidebar 
permalink: release-notes/changes-to-limits-defaults.html 
keywords: release notes, changes, updates, defaults, limits, afx storage system, afx system, afx 
summary: Erfahren Sie mehr über die Änderungen an Grenzwerten und Standardeinstellungen, die AFX-Systeme betreffen. NetApp ist bestrebt, seinen Kunden die wichtigsten Änderungen an Standardeinstellungen und Grenzwerten in jeder ONTAP-Version zu erläutern. 
---
= Änderungen an ONTAP-Grenzwerten und Standardeinstellungen, die AFX-Systeme betreffen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die Änderungen an Grenzwerten und Standardeinstellungen, die AFX-Systeme betreffen. NetApp ist bestrebt, seinen Kunden die wichtigsten Änderungen an Standardeinstellungen und Grenzwerten in jeder ONTAP-Version zu erläutern.


TIP: Um die Leistungsfähigkeit Ihres AFX-Clusters zu ermitteln, sollten Sie die im NetApp Hardware Universe and Interoperability Matrix Tool verfügbaren Details überprüfen.



[[changes-to-ontap-limits]]
== Änderungen der ONTAP Grenzwerte

[cols="1,3,1"]
|===
| Funktion | Limitänderung | In der Version geändert 


| Knoten pro Cluster  a| 
Sie können Ihren AFX Cluster auf maximal 32 Knoten erweitern. Dadurch lässt sich Ihr AFX Speichersystem an die wachsenden Anforderungen Ihrer Workloads und Anwendungen anpassen. Zu beachten ist, dass die Unterstützung für 32 Knoten mit einem eingeschränkten Funktionsumfang verfügbar ist; für Details steht das NetApp Account-Team zur Verfügung.
| ONTAP 9.19.1 


| Volumen pro FlexGroup  a| 
Die maximale Anzahl an Volumes in einem FlexGroup wurde auf 512 mit 32 Knoten erhöht. Dies ermöglicht es dem AFX-Speichersystem, die Leistungskapazitäten für größere Cluster vollständig bereitzustellen.
| ONTAP 9.19.1 
|===


[[related-information]]
== Ähnliche Informationen

* https://hwu.netapp.com/["NetApp Hardware Universe"^]
* https://imt.netapp.com/["NetApp Interoperabilitätsmatrix-Tool"^]
* https://docs.netapp.com/us-en/interoperability-matrix-tool/["Übersicht über das Interoperabilitätsmatrix-Tool"^]

