---
sidebar: sidebar 
permalink: release-notes/whats-new-9181.html 
keywords: 'afx, release notes, what"s new, 9.18.1' 
summary: Erfahren Sie mehr über die neuen Funktionen von ONTAP 9.18.1, die mit Ihrem AFX-Speichersystem verfügbar sind. 
---
= Was ist neu in ONTAP 9.18.1 für AFX-Speichersysteme?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die neuen Funktionen von ONTAP 9.18.1, die mit Ihrem AFX-Speichersystem verfügbar sind.



== Verbesserungen im Speicherressourcenmanagement

[cols="2,4"]
|===
| Aktualisieren | Beschreibung 


| Verbesserte Volumenplatzierung  a| 
NetApp AFX gleicht die Platzierung von Volumes automatisch auf alle Knoten in einem Cluster aus.  Bei früheren ONTAP Versionen basierte der Platzierungsalgorithmus auf der Anzahl der Volumes im Cluster.  Jedem Knoten wird unabhängig von der Aktivität die gleiche Anzahl an Datenträgern zugewiesen.  Ab ONTAP 9.18.1 wurde der Algorithmus so verbessert, dass er die Leistung der Knoten beim Platzieren oder Verschieben von Volumen berücksichtigt.  Dies führt zu einer verbesserten Leistungsverteilung über die Knoten im AFX-Cluster und verringert die Wahrscheinlichkeit einer Überlastung einzelner Knoten erheblich.

|===
.Ähnliche Informationen
* https://docs.netapp.com/us-en/ontap/release-notes/index.html["Highlights der ONTAP 9-Version"^]

