---
sidebar: sidebar 
permalink: release-notes/whats-new-9181.html 
keywords: 'afx, release notes, what"s new, 9.18.1' 
summary: Erfahren Sie mehr über die neuen Funktionen von ONTAP 9.18.1, die mit Ihrem AFX-Speichersystem verfügbar sind. 
---
= Was ist neu in ONTAP 9.18.1 für AFX-Speichersysteme?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die neuen Funktionen von ONTAP 9.18.1, die mit Ihrem AFX-Speichersystem verfügbar sind.


NOTE: Mit ONTAP 9.18.1 stehen für AFX mehrere neue Funktionen zur Verfügung. Einige dieser Funktionen sind spezifisch für AFX, während viele andere aus einer gemeinsamen Produktbasis stammen. Zusätzlich zu den unten beschriebenen AFX-Funktionen wird empfohlen, auch  https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9181.html["Was ist neu in ONTAP 9.18.1?"^] zu berücksichtigen.



[[security]]
== Sicherheit

[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
xref:../administer/additional-ontap-cluster.html[Zusätzliche Administratorrechte: IPsec Hardware Offload]
 a| 
Die Unterstützung für IPsec-Hardware-Offload ist auf IPv6 ausgeweitet.



 a| 
xref:../administer/additional-ontap-cluster.html[Zusätzliche Administratorrechte: OpenSSL PQC Algorithmen]
 a| 
ONTAP unterstützt kryptografische Algorithmen für SSL, die auf Postquantum-Computing basieren. Diese Algorithmen bieten zusätzlichen Schutz vor potenziellen zukünftigen Quantencomputerangriffen und sind verfügbar, wenn der SSL-FIPS-Modus deaktiviert ist.

|===


[[storage-resource-management-enhancements]]
== Verbesserungen im Speicherressourcenmanagement

[cols="2,4"]
|===
| Aktualisieren | Beschreibung 


| Verbesserte Volumenplatzierung  a| 
NetApp AFX gleicht die Platzierung von Volumes automatisch auf alle Knoten in einem Cluster aus.  Bei früheren ONTAP Versionen basierte der Platzierungsalgorithmus auf der Anzahl der Volumes im Cluster.  Jedem Knoten wird unabhängig von der Aktivität die gleiche Anzahl an Datenträgern zugewiesen.  Ab ONTAP 9.18.1 wurde der Algorithmus so verbessert, dass er die Leistung der Knoten beim Platzieren oder Verschieben von Volumen berücksichtigt.  Dies führt zu einer verbesserten Leistungsverteilung über die Knoten im AFX-Cluster und verringert die Wahrscheinlichkeit einer Überlastung einzelner Knoten erheblich.



 a| 
xref:../administer/configure-svm.html[Unterstützung für zweistufig verschachtelte QoS-Richtliniengruppen auf SVMs und Volumes]
 a| 
Sie können einer SVM und gleichzeitig den Volumes unter der SVM eine QoS-Richtlinie zuweisen.

|===


[[related-information]]
== Ähnliche Informationen

* https://docs.netapp.com/us-en/ontap/release-notes/index.html["Highlights der ONTAP 9-Version"^]

